name: Run Python script every weekday at 8am
on:
  schedule:
    - cron: "0 8 * * 1-5" # runs at 8am every weekday (Monday to Friday)

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # specify the version of Python you want to use
    - name: Run script
      run: python src/producers/update_prices.py # replace with the name of your Python script
